version: '3.8'

networks:
    web_net:
        name: web_net
        driver_opts:
            com.docker.network.bridge.name: web_net
    wp_net:
        name: wp_net
        driver_opts:
            com.docker.network.bridge.name: wp_net
    registry_net:
        name: registry_net
        driver_opts:
            com.docker.network.bridge.name: registry_net

volumes:
    wordpress_mysql_data:
        name: wordpress_mysql_data
    wordpress_data:
        name: wordpress_data
    registry_data:
        name: registry_data

services:
    registry:
        image: registry:2
        container_name: docker_registry
        networks:
            - registry_net
        volumes:
            - registry_data:/var/lib/registry

    nginx_for_registry:
        image: nginx:latest
        container_name: proxy_for_registry
        networks:
            - registry_net
        ports:
            - "5000:5000"
        depends_on:
            - registry
        volumes:
            - ./registry_nginx.conf:/etc/nginx/nginx.conf
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: on-failure
        volumes:
            - wordpress_mysql_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: Gooneh_DevOps
            MYSQL_USER: Gooneh
            MYSQL_PASSWORD: thisisveryhardpasswordnow
        networks:
            - wp_net
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            start_period: 5s
            timeout: 20s
            interval: 5s
            retries: 10

    wordpress:
        image: wordpress:latest
        container_name: wordpress
        restart: on-failure
        volumes:
            - wordpress_data:/var/www/html/
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: Gooneh
            WORDPRESS_DB_NAME: Gooneh_DevOps
            WORDPRESS_DB_PASSWORD: thisisveryhardpasswordnow
        networks:
            - wp_net
            - web_net

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - /etc/nginx/:/etc/nginx/
        networks:
            - web_net
            - wp_net
        depends_on:
            - mysql
            - wordpress